### ISSUE TITLE
odim dispatch major issues in arkimet 1.8

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#154]
`arki-scan` dispatch of odim files in arkimet 1.8 fails with exit status 0, there are at least two separate issues, the command used to dispatch files is :

```
arki-scan --yaml --dispatch=/tmp/d_crontab.info.arkimet_import.radar.volume.WCf6aozDjP/conf --copyko=/dati_sorgenti_esterne/procedure/radar/volume/error /autofs/ftpuser/radar/INPUT_MSE/MSS1833013250U.101.h5
```

1) some files give this error:
```
 [2018-11-26T13:32:33Z]Scanned from MSS1832415450U.101.h5
 [2018-11-26T13:32:33Z]Failed to store in dataset 'odimSPC': cannot open file /arkivio/arkimet/dataset/odimSPC/2018/11-20.odimh5/000147.odimh5: File exists
```

2) `arki-scan` exits with `exit 0` even when it archives the file in `error` dataset AND it copies the file in the `copyko` dir (I already tried removing the `copyko` option but the exit 0 in case of dispatch failure persists).

I'll try to isolate the issue in a test case outside our production servers

**Comment by spanezz** [comment]
I tracked the issue to here:
https://github.com/ARPA-SIMC/arkimet/blob/master/arki/runtime/arki-scan.cc#L50

The return value of dispatch is ignored, and foreach_source will return true if nothing raised an exception. This means that if everything was successfully not imported (dispatched in error dataset, copied to copyko files and so on), then arki-scan returns true.

I already have a draft fix. The question is what is the desired behaviour. I assume I should return error in case at least one data ended up in the error dataset.

What if all data imported correctly except one that was a duplicate?

**Comment by spanezz** [comment]
I pushed a fix: 9ebd91ececc2c9100313efc8f281bd34ed66c3ba

**Comment by brancomat** [comment]
Ok, I'm building a new release of arkimet.
The issue remaining about the odim importation failures seems isolated to a change of arkimet version in that particular day, I'm lowering the label priority for that.
